### ISSUE TITLE
Installaton not possible on arm architecture

### ISSUE THREAD

**Issue by Jean1995** [The-Ludwig/PANAMA#29]
I am unable to install PANAMA on my M1 MacOS, it fails with the error

```
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      cpuinfo failed, assuming no CPU features: 'flags'
      * Using Python 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)]
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 265, in <module>
        File "<string>", line 132, in get_blosc2_directories
      NotADirectoryError: Install directory for blosc2 not found in /opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Might be related to [this issue](https://github.com/PyTables/PyTables/issues/998)

**Comment by The-Ludwig** [comment]
Yes, I agree. Probably the same error as in the tables issue, since I require tables to export to hdf5.

**Comment by Jean1995** [comment]
I was able to install panama by cloning the current master of the pytables repository, explicitly exporting the paths

```
export HDF5_DIR=/opt/homebrew/opt/hdf5 
export BLOSC_DIR=/opt/homebrew/opt/c-blosc
```

installing it with 

```
pip install .
```

and then installing panama. So I hope this is fixed with the pytables 3.8.1 release.

**Comment by The-Ludwig** [comment]
@Jean1995 Can you test it out on branch [`arm`](https://github.com/The-Ludwig/PANAMA/tree/arm). I updated to pytables 3.9.0, and needed to drop support for python 3.8 (reasonable thing anyway in my opinion...)

**Comment by Jean1995** [comment]
> ... and needed to drop support for python 3.8 (reasonable thing anyway in my opinion...)...

Python 3.8 is still the default on Ubuntu 20.04 LTS, so I believe there might still be some people using it :D

**Comment by The-Ludwig** [comment]
> > ... and needed to drop support for python 3.8 (reasonable thing anyway in my opinion...)...
> 
> Python 3.8 is still the default on Ubuntu 20.04 LTS, so I believe there might still be some people using it :D

Ok, good argument. Although I doubt this software will be used with any system-level python installation... Then the branch can be merged in 2025, when Ubuntu 20 is not longer supported ;)

**Comment by The-Ludwig** [comment]
:0 ok, I need further time to look into that, someday else

**Comment by Jean1995** [comment]
> :0 ok, I need further time to look into that, someday else

Well, you have time until 2025 :)

**Comment by Jean1995** [comment]
Installation seems to be working now (I believe?)

However, trying to execute panama now gives me another error message:

```
(env) ➜  C8_history panama
Traceback (most recent call last):
  File "/opt/homebrew/bin/panama", line 5, in <module>
    from panama.cli import cli
  File "/opt/homebrew/lib/python3.11/site-packages/panama/__init__.py", line 19, in <module>
    __version__ = get_version()
                  ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/panama/__init__.py", line 14, in get_version
    with open(path) as f:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/lib/python3.11/site-packages/pyproject.toml'
```

**Comment by The-Ludwig** [comment]
@Jean1995 Can replicate the error.

**Comment by The-Ludwig** [comment]
@Jean1995 release 0.7.0 should have fixed this, can you confirm?

**Comment by Jean1995** [comment]
For my local Mac, installation is working fine now

**Comment by The-Ludwig** [comment]
Nice! But is it because you are using a newer pytables version (including python 3.9)?

**Comment by Jean1995** [comment]
Yes, I believe it is due to the newer pytables version. Old versions of panama also work now, probably because I've already intsalled a newer pytables package.

I am using Python 3.11.6 on my MacOS machine.

**Comment by The-Ludwig** [comment]
Hmmm, then I am unsure if this issue should stay open, since we can't have both ARM and python 3.8 compatibility?

**Comment by Jean1995** [comment]
Does PANAMA still support Python 3.8?

**Comment by Jean1995** [comment]
If the issue is only for Python 3.8 on arm, I believe/hope the number of affected users is pretty small.

**Comment by The-Ludwig** [comment]
> Does PANAMA still support Python 3.8?

Yes, I liked your Ubuntu argument.

**Comment by The-Ludwig** [comment]
> If the issue is only for Python 3.8 users on arm, I believe/hope the number of affected users is pretty small.

Hmmm, basically people with python 3.8 on newer macs or who simply have an old pytables version in their environment.
