### ISSUE TITLE
Save STDOUT

### ISSUE THREAD

**Issue by The-Ludwig** [The-Ludwig/PANAMA#60]
Right now, the stdout of the CORSIKA files is not saved, this should be added

**Comment by Jean1995** [comment]
This was realized with the branch 'save_output'

Is this feature supposed to be ported to main at some point?

**Comment by The-Ludwig** [comment]
@Jean1995 Yes! https://github.com/The-Ludwig/PANAMA/pull/68 
I know you used the feature, did you experience any bugs?

**Comment by Jean1995** [comment]
I don't think so, at least for my use cases (reading out runtimes from the output files), it worked without a problem.
