### ISSUE TITLE
HDF5 installation not found Mac M1 Pro Ventura

### ISSUE THREAD

**Issue by pascalgutjahr** [The-Ludwig/PANAMA#86]
The installation using `pip install corsika-panama` fails on a Mac M1 Pro with Ventura 13.6.1 because the local installation of `HDF5` is not found. 

This can be fixed by setting the correct installation path to 
`export HDF5_DIR=/opt/homebrew/opt/hdf5`

which of course requires the installation of `HDF5` using `brew install hdf5`.

**Comment by The-Ludwig** [comment]
h5py is always fun! :D Thanks for the issue. Can this be solved automatically, or should we just put a comment in the installation instructions?

**Comment by The-Ludwig** [comment]
This is "fixed" by making pytables an optional dependency with #89
