### ISSUE TITLE
Road to 1.0

### ISSUE THREAD

**Issue by The-Ludwig** [The-Ludwig/PANAMA#91]
I am working on the very last issues and I think after updating the documentation, this package is ready for a 1.0 release.

I have a lot of ideas for this package which might improve and extend it, but I think the current scope is very reasonable. 
For a 2.0 release some features may be:
- `panama install 77420` asks for the corsika password and downloads and installs/compiles the given corsika version  to a given location (this would be a modularization and extention of the script in the admin folder. But may be we don't want to steal coconut the show)
- yaml steering: instead of steering cards, write one steering card where everything is replaced by a template, which is then filled in by values from a yaml file. optionally override this on the command line. 

@Jean1995 as you and I are currently the only ones using this, I guess (maybe @pgutjahr?): Are there any more features you might want to see for a 1.0?

**Comment by Jean1995** [comment]
I am pretty happy with the features currently available :)

**Comment by pascalgutjahr** [comment]
I fully agree! Go for it!
