### ISSUE TITLE
Start with different EVTNR

### ISSUE THREAD

**Issue by Jean1995** [The-Ludwig/PANAMA#95]
I believe at the moment, the first event always starts with the event number 1

It would be nice if one could optionally specific a different start number, e.g., if one wants to organize the events in a specific way :)

**Comment by The-Ludwig** [comment]
Working on the feature RN, fairly simple.
So long as a workaround: In your CORSIKA input card just replace the {first_event_idx} with what you want, should not prduce any errors or unexpected behaviour.

**Comment by Jean1995** [comment]
Is this independent of the naming of the files, i.e., DATXXXXXX?

**Comment by The-Ludwig** [comment]
Yes, that should be the run numbers, not the event numbers

**Comment by The-Ludwig** [comment]
@Jean1995 #96
